# Generated by Django 6.0.3 on 2026-03-09 23:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Référence')),
                ('date_vente', models.DateTimeField(auto_now_add=True, verbose_name='Date de vente')),
                ('total_ttc', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Total TTC')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('completee', 'Complétée'), ('annulee', 'Annulée')], default='completee', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date_vente'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire au moment de la vente')),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sous-total')),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='medicaments.medicament', verbose_name='Médicament')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='ventes.vente', verbose_name='Vente')),
            ],
            options={
                'verbose_name': 'Ligne de vente',
                'verbose_name_plural': 'Lignes de vente',
            },
        ),
    ]
